### PR TITLE
Added permanent patcher that modifies log4j jarfile

### PR DESCRIPTION
**Pull request by TudbuT**

### CODE REVIEW

**Comment by TudbuT** [comment]
My solution does not work yet. I will reopen this when im done

**Comment by TudbuT** [comment]
I fixed my solution

**Review by CyberFlameGO — APPROVED** [review]

**Comment by Cybereason** [comment]
I love this solution, but would like to get a little bit of community feedback.
We've built this very defensively which is why we're not making any permanent changes - I'd love to hear some feedback about adopting your patch.

In any case, I've revised the payload to support older versions, so I'd love for you to update your patch.

**Comment by TudbuT** [comment]
OK! I will fix my patch to work with the current version

**Comment by TudbuT** [comment]
I merged the current version and my patch. I will now make a version of the patch that works on old versions.

**Comment by TudbuT** [comment]
Quick question: is it ok if the permanent fix only works with a jdk and not a jre? If not, itll take me a bit longer to do.

**Comment by CyberFlameGO** [comment]
> I merged the current version and my patch. I will now make a version of the patch that works on old versions.

You sure? It’s not showing up, did you push it if you merged it locally?

**Comment by TudbuT** [comment]
> > I merged the current version and my patch. I will now make a version of the patch that works on old versions.
> 
> You sure? It’s not showing up, did you push it if you merged it locally?

I hadn't pushed yet, but now i have, and I'm also done fixing the permanent patcher for older versions.

**Comment by TudbuT** [comment]
I also tested my changes locally, and it seems to still be working on 2.14.1.
I will now check for 2.9.

**Comment by TudbuT** [comment]
Once the jar is modified, it will crash entirely on 2.9. Is that OK or should i try to change it?

**Comment by TudbuT** [comment]
> Once the jar is modified, it will crash entirely on 2.9. Is that OK or should i try to change it?

I fixed the crash anyways

**Comment by TudbuT** [comment]
Merged. My permanent patcher already removed JndiLookup, so i didn't have to change that.

**Comment by cr-mitmit** [comment]
What's your motivation on all three changes?
Specifically - if we simply remove JndiLookup, the plugin won't load (look at the Interpolator code where the plugin is loaded?)

Why would we want additionally to change Constants and Log4j2Plugins.dat?

**Comment by TudbuT** [comment]
Changing Log4j2Plugins.dat is required, otherwise 2.9 will crash if JndiLookup is not there

**Comment by TudbuT** [comment]
Modifying Constants isn't required, but it feels more thorough.

**Comment by TudbuT** [comment]
If you don't like my changes, feel free to close this pull request. I don't really care about this enough to argue about it, i'm just trying to help people, which i can do without this being merged since people can use the fork itself.

**Comment by cr-mitmit** [comment]
No offense intended - was just asking for the rationale.

**Pull request merged**
